// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gdl {

	using System;
	using System.Collections;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public class Stock {

		public static string Close {
			 get { return "gdl-close"; }
		}
		public static string MenuLeft {
			 get { return "gdl-menu-left"; }
		}
		public static string MenuRight {
			 get { return "gdl-menu-right"; }
		}
#endregion
	}
}
