// This file was generated by the Gtk# Code generator.
// Any changes made will be lost if regenerated.

namespace GtkMozEmbedSharp {

	using System;

	public delegate void NewWindowHandler(object o, NewWindowArgs args);

	public class NewWindowArgs : GtkSharp.SignalArgs {
		public GtkMozEmbed.EmbedWidget NewEmbed{
			set {
				Args[0] = (GtkMozEmbed.EmbedWidget) value;
			}
		}

		public uint Chromemask{
			get {
				return (uint) Args[1];
			}
		}

	}
}
