//
// StockIcons.cs
//
// Author: Gustavo Giraldez <gustavo.giraldez@gmx.net>
//
// Copyright (C) 2004 Gustavo Giraldez.
//

using System;
using System.Collections;

namespace MonoDevelop.Gui {
	public class Stock {
		
		static Gtk.IconFactory iconFactory = null;
		static Hashtable stockMappings = null;
		
		public static void CreateIconFactory ()
		{
			iconFactory = new Gtk.IconFactory ();

			// FIXME: remove this when all MonoDevelop is using Gtk+
			// stock icons
			stockMappings = new Hashtable ();

			SetupStockOverrides ();
			SetupIconFactory ();
			iconFactory.AddDefault ();
		}

		static void AddToIconFactory (string stockId,
		                              string filename,
		                              Gtk.IconSize iconSize)
		{
			if (stockMappings [filename] != null)
				// stock icon overriden
				return;
			
			try {
				Gdk.Pixbuf pixbuf = new Gdk.Pixbuf ("../data/resources/icons/"
				                                    + filename);

				Gtk.IconSet iconSet = iconFactory.Lookup (stockId);
				if (iconSet == null || iconSet.Handle == IntPtr.Zero) {
					// Gtk.IconFactory.Lookup never returns null, but
					// the actual underlying GObject might be NULL
					// (bug in Gtk#?)
					iconSet = new Gtk.IconSet ();
					iconFactory.Add (stockId, iconSet);
				}

				Gtk.IconSource source = new Gtk.IconSource ();
				source.Pixbuf = pixbuf;
				source.Size = iconSize;
				iconSet.AddSource (source);

				// FIXME: temporary hack to retrieve the correct icon
				// from the filename
				stockMappings.Add (filename, stockId);
			}
			catch (GLib.GException ex) {
				// just discard the exception, the icon simply can't be
				// loaded
				Console.WriteLine ("Warning: can't load " + filename +
				                   " icon file");
			}
		}

		static void AddToIconFactory (string stockId, string filename)
		{
			AddToIconFactory (stockId, filename, Gtk.IconSize.Invalid);
		}

		public static string GetStockId (string filename)
		{
			return (string) stockMappings [filename];
		}

		static void SetupStockOverrides ()
		{
			// Override some mapped stock ids
			stockMappings ["Icons.16x16.AboutIcon"] = Gnome.Stock.About;
			stockMappings ["Icons.16x16.CloseIcon"] = Gtk.Stock.Close;
			stockMappings ["Icons.16x16.CopyIcon"] = Gtk.Stock.Copy;
			stockMappings ["Icons.16x16.CutIcon"] = Gtk.Stock.Cut;
			stockMappings ["Icons.16x16.DeleteIcon"] = Gtk.Stock.Delete;
			stockMappings ["Icons.16x16.FindIcon"] = Gtk.Stock.Find;
			stockMappings ["Icons.16x16.HelpIcon"] = Gtk.Stock.Help;
			stockMappings ["Icons.16x16.NewDocumentIcon"] = Gtk.Stock.New;
			stockMappings ["Icons.16x16.NextWindowIcon"] = Gtk.Stock.GoForward;
			stockMappings ["Icons.16x16.OpenFileIcon"] = Gtk.Stock.Open;
			stockMappings ["Icons.16x16.Options"] = Gtk.Stock.Preferences;
			stockMappings ["Icons.16x16.PasteIcon"] = Gtk.Stock.Paste;
			stockMappings ["Icons.16x16.PreView"] = Gtk.Stock.PrintPreview;
			stockMappings ["Icons.16x16.PrevWindowIcon"] = Gtk.Stock.GoBack;
			stockMappings ["Icons.16x16.Print"] = Gtk.Stock.Print;
			stockMappings ["Icons.16x16.QuitIcon"] = Gtk.Stock.Quit;
			stockMappings ["Icons.16x16.RedoIcon"] = Gtk.Stock.Redo;
			stockMappings ["Icons.16x16.ReplaceIcon"] = Gtk.Stock.FindAndReplace;
			stockMappings ["Icons.16x16.RunProgramIcon"] = Gtk.Stock.Execute;
			stockMappings ["Icons.16x16.SaveAsIcon"] = Gtk.Stock.SaveAs;
			stockMappings ["Icons.16x16.SaveIcon"] = Gtk.Stock.Save;
			stockMappings ["Icons.16x16.UndoIcon"] = Gtk.Stock.Undo;
			stockMappings ["Icons.16x16.Error"] = Gtk.Stock.DialogError;
			stockMappings ["Icons.16x16.Warning"] = Gtk.Stock.DialogWarning;
			stockMappings ["Icons.16x16.Information"] = Gtk.Stock.DialogInfo;
			stockMappings ["Icons.16x16.Question"] = Gtk.Stock.DialogQuestion;
		}

#region Autogenerated code
		static void SetupIconFactory ()
		{
			AddToIconFactory ("md-about-icon", "Icons.16x16.AboutIcon");
			AddToIconFactory ("md-adjust-background-color", "Icons.16x16.AdjustBackgroundColor");
			AddToIconFactory ("md-adjust-color", "Icons.16x16.AdjustColor");
			AddToIconFactory ("md-asp-file-icon", "Icons.32x32.ASPFileIcon");
			AddToIconFactory ("md-assembly", "Icons.16x16.Assembly");
			AddToIconFactory ("md-bold-text", "Icons.16x16.BoldText");
			AddToIconFactory ("md-browser-after", "Icons.16x16.BrowserAfter");
			AddToIconFactory ("md-browser-before", "Icons.16x16.BrowserBefore");
			AddToIconFactory ("md-browser-cancel", "Icons.16x16.BrowserCancel");
			AddToIconFactory ("md-browser-refresh", "Icons.16x16.BrowserRefresh");
			AddToIconFactory ("md-build-combine", "Icons.16x16.BuildCombine");
			AddToIconFactory ("md-build-current-selected-project", "Icons.16x16.BuildCurrentSelectedProject");
			AddToIconFactory ("md-c#-file-empty-file", "C#.File.EmptyFile");
			AddToIconFactory ("md-c#-file-form", "C#.File.Form");
			AddToIconFactory ("md-c#-file-full-file", "C#.File.FullFile");
			AddToIconFactory ("md-c#-file-icon", "C#.FileIcon");
			AddToIconFactory ("md-c#-file-new-class", "C#.File.NewClass");
			AddToIconFactory ("md-c#-file-web-file", "C#.File.WebFile");
			AddToIconFactory ("md-c#-project-dos-project", "C#.Project.DOSProject");
			AddToIconFactory ("md-c#-project-empty-project", "C#.Project.EmptyProject");
			AddToIconFactory ("md-c#-project-form", "C#.Project.Form");
			AddToIconFactory ("md-c#-project-full-project", "C#.Project.FullProject");
			AddToIconFactory ("md-c#-project-icon", "C#.ProjectIcon");
			AddToIconFactory ("md-c#-project-library", "C#.Project.Library");
			AddToIconFactory ("md-c#-project-service-project", "C#.Project.ServiceProject");
			AddToIconFactory ("md-c#-project-user-control", "C#.Project.UserControl");
			AddToIconFactory ("md-c#-project-web-project", "C#.Project.WebProject");
			AddToIconFactory ("md-c++-file-empty-file", "C++.File.EmptyFile");
			AddToIconFactory ("md-c++-file-form", "C++.File.Form");
			AddToIconFactory ("md-c++-file-full-file", "C++.File.FullFile");
			AddToIconFactory ("md-c++-file-icon", "C++.FileIcon");
			AddToIconFactory ("md-c++-file-new-class", "C++.File.NewClass");
			AddToIconFactory ("md-c++-file-web-file", "C++.File.WebFile");
			AddToIconFactory ("md-c++-project-dos-project", "C++.Project.DOSProject");
			AddToIconFactory ("md-c++-project-empty-project", "C++.Project.EmptyProject");
			AddToIconFactory ("md-c++-project-form", "C++.Project.Form");
			AddToIconFactory ("md-c++-project-full-project", "C++.Project.FullProject");
			AddToIconFactory ("md-c++-project-icon", "C++.ProjectIcon");
			AddToIconFactory ("md-c++-project-library", "C++.Project.Library");
			AddToIconFactory ("md-c++-project-service-project", "C++.Project.ServiceProject");
			AddToIconFactory ("md-c++-project-user-control", "C++.Project.UserControl");
			AddToIconFactory ("md-c++-project-web-project", "C++.Project.WebProject");
			AddToIconFactory ("md-cancel-icon", "Icons.16x16.CancelIcon");
			AddToIconFactory ("md-cdrom", "Icons.16x16.CDROM");
			AddToIconFactory ("md-center", "Icons.16x16.Center");
			AddToIconFactory ("md-class", "Icons.16x16.Class");
			AddToIconFactory ("md-class-browser-icon", "Icons.ClassBrowserIcon");
			AddToIconFactory ("md-clear-all-bookmarks", "Icons.16x16.ClearAllBookmarks");
			AddToIconFactory ("md-close-all-documents", "Icons.16x16.CloseAllDocuments");
			AddToIconFactory ("md-close-combine-icon", "Icons.16x16.CloseCombineIcon");
			AddToIconFactory ("md-closed-folder-bitmap", "Icons.16x16.ClosedFolderBitmap");
			AddToIconFactory ("md-closed-option-folder", "Icons.16x16.ClosedOptionFolder");
			AddToIconFactory ("md-closed-reference-folder", "Icons.16x16.ClosedReferenceFolder");
			AddToIconFactory ("md-closed-resource-folder", "Icons.16x16.ClosedResourceFolder");
			AddToIconFactory ("md-combine-icon", "Icons.16x16.CombineIcon", Gtk.IconSize.Menu);
			AddToIconFactory ("md-combine-icon", "Icons.32x32.CombineIcon", Gtk.IconSize.Dnd);
			AddToIconFactory ("md-comment-region", "Icons.16x16.CommentRegion");
			AddToIconFactory ("md-copy-icon", "Icons.16x16.CopyIcon");
			AddToIconFactory ("md-copy-left-icon", "Icons.16x16.CopyLeftIcon");
			AddToIconFactory ("md-cut-icon", "Icons.16x16.CutIcon");
			AddToIconFactory ("md-delegate", "Icons.16x16.Delegate");
			AddToIconFactory ("md-delete-icon", "Icons.16x16.DeleteIcon");
			AddToIconFactory ("md-design-panel", "Icons.16x16.DesignPanel");
			AddToIconFactory ("md-desktop", "Icons.16x16.Desktop");
			AddToIconFactory ("md-drive", "Icons.16x16.DRIVE");
			AddToIconFactory ("md-empty", "Icons.16x16.Empty");
			AddToIconFactory ("md-empty-file-icon", "Icons.32x32.EmptyFileIcon");
			AddToIconFactory ("md-empty-project-icon", "Icons.32x32.EmptyProjectIcon");
			AddToIconFactory ("md-enum", "Icons.16x16.Enum");
			AddToIconFactory ("md-error", "Icons.16x16.Error", Gtk.IconSize.Menu);
			AddToIconFactory ("md-error", "Icons.32x32.Error", Gtk.IconSize.Dnd);
			AddToIconFactory ("md-event", "Icons.16x16.Event");
			AddToIconFactory ("md-field", "Icons.16x16.Field");
			AddToIconFactory ("md-file-scout-icon", "Icons.FileScoutIcon");
			AddToIconFactory ("md-file-xml-icon", "FileIcons.XmlIcon");
			AddToIconFactory ("md-find-icon", "Icons.16x16.FindIcon");
			AddToIconFactory ("md-find-in-files", "Icons.16x16.FindInFiles");
			AddToIconFactory ("md-find-next-icon", "Icons.16x16.FindNextIcon");
			AddToIconFactory ("md-floppy", "Icons.16x16.FLOPPY");
			AddToIconFactory ("md-forms-designer-align-bottoms", "Icons.16x16.FormsDesigner.AlignBottoms");
			AddToIconFactory ("md-forms-designer-align-centers", "Icons.16x16.FormsDesigner.AlignCenters");
			AddToIconFactory ("md-forms-designer-align-lefts", "Icons.16x16.FormsDesigner.AlignLefts");
			AddToIconFactory ("md-forms-designer-align-middles", "Icons.16x16.FormsDesigner.AlignMiddles");
			AddToIconFactory ("md-forms-designer-align-rights", "Icons.16x16.FormsDesigner.AlignRights");
			AddToIconFactory ("md-forms-designer-align-to-grid", "Icons.16x16.FormsDesigner.AlignToGrid");
			AddToIconFactory ("md-forms-designer-align-tops", "Icons.16x16.FormsDesigner.AlignTops");
			AddToIconFactory ("md-forms-designer-bring-to-front", "Icons.16x16.FormsDesigner.BringToFront");
			AddToIconFactory ("md-forms-designer-center-horizontally", "Icons.16x16.FormsDesigner.CenterHorizontally");
			AddToIconFactory ("md-forms-designer-center-vertically", "Icons.16x16.FormsDesigner.CenterVertically");
			AddToIconFactory ("md-forms-designer-decrease-horizontal-space", "Icons.16x16.FormsDesigner.DecreaseHorizontalSpace");
			AddToIconFactory ("md-forms-designer-decrease-vertical-space", "Icons.16x16.FormsDesigner.DecreaseVerticalSpace");
			AddToIconFactory ("md-forms-designer-equalize-horizontal-space", "Icons.16x16.FormsDesigner.EqualizeHorizontalSpace");
			AddToIconFactory ("md-forms-designer-equalize-vertical-space", "Icons.16x16.FormsDesigner.EqualizeVerticalSpace");
			AddToIconFactory ("md-forms-designer-increase-horizontal-space", "Icons.16x16.FormsDesigner.IncreaseHorizontalSpace");
			AddToIconFactory ("md-forms-designer-increase-vertical-space", "Icons.16x16.FormsDesigner.IncreaseVerticalSpace");
			AddToIconFactory ("md-forms-designer-lock-controls", "Icons.16x16.FormsDesigner.LockControls");
			AddToIconFactory ("md-forms-designer-make-same-height", "Icons.16x16.FormsDesigner.MakeSameHeight");
			AddToIconFactory ("md-forms-designer-make-same-size", "Icons.16x16.FormsDesigner.MakeSameSize");
			AddToIconFactory ("md-forms-designer-make-same-width", "Icons.16x16.FormsDesigner.MakeSameWidth");
			AddToIconFactory ("md-forms-designer-pointer-icon", "Icons.16x16.FormsDesigner.PointerIcon");
			AddToIconFactory ("md-forms-designer-remove-horizontal-space", "Icons.16x16.FormsDesigner.RemoveHorizontalSpace");
			AddToIconFactory ("md-forms-designer-remove-vertical-space", "Icons.16x16.FormsDesigner.RemoveVerticalSpace");
			AddToIconFactory ("md-forms-designer-send-to-back", "Icons.16x16.FormsDesigner.SendToBack");
			AddToIconFactory ("md-forms-designer-show-tab-order", "Icons.16x16.FormsDesigner.ShowTabOrder");
			AddToIconFactory ("md-forms-designer-size-to-grid", "Icons.16x16.FormsDesigner.SizeToGrid");
			AddToIconFactory ("md-forms-designer-view-code", "Icons.16x16.FormsDesigner.ViewCode");
			AddToIconFactory ("md-full-screen", "Icons.16x16.FullScreen");
			AddToIconFactory ("md-goto-nextbookmark", "Icons.16x16.GotoNextbookmark");
			AddToIconFactory ("md-goto-prevbookmark", "Icons.16x16.GotoPrevbookmark");
			AddToIconFactory ("md-help-closed-folder", "Icons.16x16.HelpClosedFolder");
			AddToIconFactory ("md-help-icon", "Icons.16x16.HelpIcon");
			AddToIconFactory ("md-help-open-folder", "Icons.16x16.HelpOpenFolder");
			AddToIconFactory ("md-help-topic", "Icons.16x16.HelpTopic");
			AddToIconFactory ("md-html-class", "Icons.16x16.UMLClass");
			AddToIconFactory ("md-html-elements-anchor-element", "Icons.16x16.HtmlElements.AnchorElement");
			AddToIconFactory ("md-html-elements-button-element", "Icons.16x16.HtmlElements.ButtonElement");
			AddToIconFactory ("md-html-elements-div-element", "Icons.16x16.HtmlElements.DivElement");
			AddToIconFactory ("md-html-elements-element", "Icons.16x16.HtmlElements.Element");
			AddToIconFactory ("md-html-elements-field-set-element", "Icons.16x16.HtmlElements.FieldSetElement");
			AddToIconFactory ("md-html-elements-form-element", "Icons.16x16.HtmlElements.FormElement");
			AddToIconFactory ("md-html-elements-horizontal-rule-element", "Icons.16x16.HtmlElements.HorizontalRuleElement");
			AddToIconFactory ("md-html-elements-i-frame-element", "Icons.16x16.HtmlElements.IFrameElement");
			AddToIconFactory ("md-html-elements-image-element", "Icons.16x16.HtmlElements.ImageElement");
			AddToIconFactory ("md-html-elements-input-button-element", "Icons.16x16.HtmlElements.InputButtonElement");
			AddToIconFactory ("md-html-elements-input-check-box-element", "Icons.16x16.HtmlElements.InputCheckBoxElement");
			AddToIconFactory ("md-html-elements-input-file-element", "Icons.16x16.HtmlElements.InputFileElement");
			AddToIconFactory ("md-html-elements-input-hidden-element", "Icons.16x16.HtmlElements.InputHiddenElement");
			AddToIconFactory ("md-html-elements-input-image-element", "Icons.16x16.HtmlElements.InputImageElement");
			AddToIconFactory ("md-html-elements-input-password-element", "Icons.16x16.HtmlElements.InputPasswordElement");
			AddToIconFactory ("md-html-elements-input-radio-element", "Icons.16x16.HtmlElements.InputRadioElement");
			AddToIconFactory ("md-html-elements-input-reset-element", "Icons.16x16.HtmlElements.InputResetElement");
			AddToIconFactory ("md-html-elements-input-submit-element", "Icons.16x16.HtmlElements.InputSubmitElement");
			AddToIconFactory ("md-html-elements-input-text-element", "Icons.16x16.HtmlElements.InputTextElement");
			AddToIconFactory ("md-html-elements-label-element", "Icons.16x16.HtmlElements.LabelElement");
			AddToIconFactory ("md-html-elements-list-box-element", "Icons.16x16.HtmlElements.ListBoxElement");
			AddToIconFactory ("md-html-elements-panel-element", "Icons.16x16.HtmlElements.PanelElement");
			AddToIconFactory ("md-html-elements-select-element", "Icons.16x16.HtmlElements.SelectElement");
			AddToIconFactory ("md-html-elements-span-element", "Icons.16x16.HtmlElements.SpanElement");
			AddToIconFactory ("md-html-elements-table-element", "Icons.16x16.HtmlElements.TableElement");
			AddToIconFactory ("md-html-elements-text-area-element", "Icons.16x16.HtmlElements.TextAreaElement");
			AddToIconFactory ("md-html-file-icon", "Icons.32x32.HTMLFileIcon");
			AddToIconFactory ("md-html-icon", "Icons.16x16.HTMLIcon");
			AddToIconFactory ("md-html-implementation", "Icons.16x16.UMLImplementation");
			AddToIconFactory ("md-html-note", "Icons.16x16.UMLNote");
			AddToIconFactory ("md-html-structure", "Icons.16x16.UMLStructure");
			AddToIconFactory ("md-ildasm", "Icons.16x16.ILDasm");
			AddToIconFactory ("md-indent", "Icons.16x16.Indent");
			AddToIconFactory ("md-information", "Icons.16x16.Information", Gtk.IconSize.Menu);
			AddToIconFactory ("md-information", "Icons.32x32.Information", Gtk.IconSize.Dnd);
			AddToIconFactory ("md-interface", "Icons.16x16.Interface");
			AddToIconFactory ("md-internal-class", "Icons.16x16.InternalClass");
			AddToIconFactory ("md-internal-delegate", "Icons.16x16.InternalDelegate");
			AddToIconFactory ("md-internal-enum", "Icons.16x16.InternalEnum");
			AddToIconFactory ("md-internal-event", "Icons.16x16.InternalEvent");
			AddToIconFactory ("md-internal-field", "Icons.16x16.InternalField");
			AddToIconFactory ("md-internal-interface", "Icons.16x16.InternalInterface");
			AddToIconFactory ("md-internal-method", "Icons.16x16.InternalMethod");
			AddToIconFactory ("md-internal-property", "Icons.16x16.InternalProperty");
			AddToIconFactory ("md-internal-struct", "Icons.16x16.InternalStruct");
			AddToIconFactory ("md-italic-text", "Icons.16x16.ItalicText");
			AddToIconFactory ("md-java-file-empty-file", "Java.File.EmptyFile");
			AddToIconFactory ("md-java-file-form", "Java.File.Form");
			AddToIconFactory ("md-java-file-full-file", "Java.File.FullFile");
			AddToIconFactory ("md-java-file-icon", "Java.FileIcon");
			AddToIconFactory ("md-java-file-new-class", "Java.File.NewClass");
			AddToIconFactory ("md-java-file-web-file", "Java.File.WebFile");
			AddToIconFactory ("md-java-project-dos-project", "Java.Project.DOSProject");
			AddToIconFactory ("md-java-project-empty-project", "Java.Project.EmptyProject");
			AddToIconFactory ("md-java-project-form", "Java.Project.Form");
			AddToIconFactory ("md-java-project-full-project", "Java.Project.FullProject");
			AddToIconFactory ("md-java-project-icon", "Java.ProjectIcon");
			AddToIconFactory ("md-java-project-library", "Java.Project.Library");
			AddToIconFactory ("md-java-project-service-project", "Java.Project.ServiceProject");
			AddToIconFactory ("md-java-project-user-control", "Java.Project.UserControl");
			AddToIconFactory ("md-java-project-web-project", "Java.Project.WebProject");
			AddToIconFactory ("md-jscript-file-empty-file", "JScript.File.EmptyFile");
			AddToIconFactory ("md-jscript-file-form", "JScript.File.Form");
			AddToIconFactory ("md-jscript-file-full-file", "JScript.File.FullFile");
			AddToIconFactory ("md-jscript-file-icon", "JScript.FileIcon");
			AddToIconFactory ("md-jscript-file-new-class", "JScript.File.NewClass");
			AddToIconFactory ("md-jscript-file-web-file", "JScript.File.WebFile");
			AddToIconFactory ("md-jscript-project-dos-project", "JScript.Project.DOSProject");
			AddToIconFactory ("md-jscript-project-empty-project", "JScript.Project.EmptyProject");
			AddToIconFactory ("md-jscript-project-form", "JScript.Project.Form");
			AddToIconFactory ("md-jscript-project-full-project", "JScript.Project.FullProject");
			AddToIconFactory ("md-jscript-project-icon", "JScript.ProjectIcon");
			AddToIconFactory ("md-jscript-project-library", "JScript.Project.Library");
			AddToIconFactory ("md-jscript-project-service-project", "JScript.Project.ServiceProject");
			AddToIconFactory ("md-jscript-project-user-control", "JScript.Project.UserControl");
			AddToIconFactory ("md-jscript-project-web-project", "JScript.Project.WebProject");
			AddToIconFactory ("md-large-icon", "Icons.16x16.LargeIconsIcon");
			AddToIconFactory ("md-left", "Icons.16x16.Left");
			AddToIconFactory ("md-library", "Icons.16x16.Library");
			AddToIconFactory ("md-literal", "Icons.16x16.Literal");
			AddToIconFactory ("md-lower-to-upper-case", "Icons.16x16.LowerToUpperCase");
			AddToIconFactory ("md-method", "Icons.16x16.Method");
			AddToIconFactory ("md-misc-files", "Icons.16x16.MiscFiles");
			AddToIconFactory ("md-my-computer", "Icons.16x16.MyComputer");
			AddToIconFactory ("md-name-space", "Icons.16x16.NameSpace");
			AddToIconFactory ("md-network", "Icons.16x16.NETWORK");
			AddToIconFactory ("md-new-document-icon", "Icons.16x16.NewDocumentIcon");
			AddToIconFactory ("md-new-folder-icon", "Icons.16x16.NewFolderIcon");
			AddToIconFactory ("md-new-project-icon", "Icons.16x16.NewProjectIcon");
			AddToIconFactory ("md-next-window-icon", "Icons.16x16.NextWindowIcon");
			AddToIconFactory ("md-open-assembly", "Icons.16x16.OpenAssembly");
			AddToIconFactory ("md-open-file-icon", "Icons.16x16.OpenFileIcon");
			AddToIconFactory ("md-open-folder-bitmap", "Icons.16x16.OpenFolderBitmap");
			AddToIconFactory ("md-open-option-folder", "Icons.16x16.OpenOptionFolder");
			AddToIconFactory ("md-open-project-icon", "Icons.16x16.OpenProjectIcon");
			AddToIconFactory ("md-open-reference-folder", "Icons.16x16.OpenReferenceFolder");
			AddToIconFactory ("md-open-resource-folder", "Icons.16x16.OpenResourceFolder");
			AddToIconFactory ("md-options", "Icons.16x16.Options");
			AddToIconFactory ("md-out-dent", "Icons.16x16.OutDent");
			AddToIconFactory ("md-output-icon", "Icons.16x16.OutputIcon");
			AddToIconFactory ("md-paste-icon", "Icons.16x16.PasteIcon");
			AddToIconFactory ("md-personal-files", "Icons.16x16.PersonalFiles");
			AddToIconFactory ("md-pre-view", "Icons.16x16.PreView");
			AddToIconFactory ("md-prev-window-icon", "Icons.16x16.PrevWindowIcon");
			AddToIconFactory ("md-print", "Icons.16x16.Print");
			AddToIconFactory ("md-private-class", "Icons.16x16.PrivateClass");
			AddToIconFactory ("md-private-delegate", "Icons.16x16.PrivateDelegate");
			AddToIconFactory ("md-private-enum", "Icons.16x16.PrivateEnum");
			AddToIconFactory ("md-private-event", "Icons.16x16.PrivateEvent");
			AddToIconFactory ("md-private-field", "Icons.16x16.PrivateField");
			AddToIconFactory ("md-private-interface", "Icons.16x16.PrivateInterface");
			AddToIconFactory ("md-private-method", "Icons.16x16.PrivateMethod");
			AddToIconFactory ("md-private-property", "Icons.16x16.PrivateProperty");
			AddToIconFactory ("md-private-struct", "Icons.16x16.PrivateStruct");
			AddToIconFactory ("md-project-scout-icon", "Icons.ProjectScoutIcon");
			AddToIconFactory ("md-properties-icon", "Icons.16x16.PropertiesIcon");
			AddToIconFactory ("md-property", "Icons.16x16.Property");
			AddToIconFactory ("md-protected-class", "Icons.16x16.ProtectedClass");
			AddToIconFactory ("md-protected-delegate", "Icons.16x16.ProtectedDelegate");
			AddToIconFactory ("md-protected-enum", "Icons.16x16.ProtectedEnum");
			AddToIconFactory ("md-protected-event", "Icons.16x16.ProtectedEvent");
			AddToIconFactory ("md-protected-field", "Icons.16x16.ProtectedField");
			AddToIconFactory ("md-protected-interface", "Icons.16x16.ProtectedInterface");
			AddToIconFactory ("md-protected-method", "Icons.16x16.ProtectedMethod");
			AddToIconFactory ("md-protected-property", "Icons.16x16.ProtectedProperty");
			AddToIconFactory ("md-protected-struct", "Icons.16x16.ProtectedStruct");
			AddToIconFactory ("md-question", "Icons.16x16.Question", Gtk.IconSize.Menu);
			AddToIconFactory ("md-question", "Icons.32x32.Question", Gtk.IconSize.Dnd);
			AddToIconFactory ("md-redo-icon", "Icons.16x16.RedoIcon");
			AddToIconFactory ("md-reference", "Icons.16x16.Reference");
			AddToIconFactory ("md-replace-icon", "Icons.16x16.ReplaceIcon");
			AddToIconFactory ("md-replace-in-files", "Icons.16x16.ReplaceInFiles");
			AddToIconFactory ("md-resource-editorbmp", "Icons.16x16.ResourceEditor.bmp");
			AddToIconFactory ("md-resource-editorcursor", "Icons.16x16.ResourceEditor.cursor");
			AddToIconFactory ("md-resource-editoricon", "Icons.16x16.ResourceEditor.icon");
			AddToIconFactory ("md-resource-editorobj", "Icons.16x16.ResourceEditor.obj");
			AddToIconFactory ("md-resource-editorstring", "Icons.16x16.ResourceEditor.string");
			AddToIconFactory ("md-resource-file-icon", "Icons.16x16.ResourceFileIcon", Gtk.IconSize.Menu);
			AddToIconFactory ("md-resource-file-icon", "Icons.32x32.ResourceFileIcon", Gtk.IconSize.Dnd);
			AddToIconFactory ("md-right", "Icons.16x16.Right");
			AddToIconFactory ("md-run-program-icon", "Icons.16x16.RunProgramIcon");
			AddToIconFactory ("md-save-all-icon", "Icons.16x16.SaveAllIcon");
			AddToIconFactory ("md-save-icon", "Icons.16x16.SaveIcon");
			AddToIconFactory ("md-selection-arrow", "Icons.16x16.SelectionArrow");
			AddToIconFactory ("md-sharp-develop-icon", "Icons.SharpDevelopIcon");
			AddToIconFactory ("md-shell", "Icons.16x16.Shell");
			AddToIconFactory ("md-side-bar-document", "Icons.16x16.SideBarDocument");
			AddToIconFactory ("md-small-icon", "Icons.16x16.SmallIconsIcon");
			AddToIconFactory ("md-solution-icon", "Icons.16x16.SolutionIcon");
			AddToIconFactory ("md-split-window", "Icons.16x16.SplitWindow");
			AddToIconFactory ("md-struct", "Icons.16x16.Struct");
			AddToIconFactory ("md-sub-types", "Icons.16x16.SubTypes");
			AddToIconFactory ("md-super-types", "Icons.16x16.SuperTypes");
			AddToIconFactory ("md-task-list-icon", "Icons.16x16.TaskListIcon");
			AddToIconFactory ("md-text-file-icon", "Icons.16x16.TextFileIcon", Gtk.IconSize.Menu);
			AddToIconFactory ("md-text-file-icon", "Icons.32x32.TextFileIcon", Gtk.IconSize.Dnd);
			AddToIconFactory ("md-tip-of-the-day", "Icons.16x16.TipOfTheDay");
			AddToIconFactory ("md-tip-of-the-day-icon", "Icons.TipOfTheDayIcon");
			AddToIconFactory ("md-toggle-bookmark", "Icons.16x16.ToggleBookmark");
			AddToIconFactory ("md-tool-bar", "Icons.16x16.ToolBar");
			AddToIconFactory ("md-underline-text", "Icons.16x16.UnderlineText");
			AddToIconFactory ("md-undo-icon", "Icons.16x16.UndoIcon");
			AddToIconFactory ("md-upper-to-lower-case", "Icons.16x16.UpperToLowerCase");
			AddToIconFactory ("md-vb-file-empty-file", "VB.File.EmptyFile");
			AddToIconFactory ("md-vb-file-form", "VB.File.Form");
			AddToIconFactory ("md-vb-file-full-file", "VB.File.FullFile");
			AddToIconFactory ("md-vb-file-icon", "VB.FileIcon");
			AddToIconFactory ("md-vb-file-new-class", "VB.File.NewClass");
			AddToIconFactory ("md-vb-file-web-file", "VB.File.WebFile");
			AddToIconFactory ("md-vb-project-dos-project", "VB.Project.DOSProject");
			AddToIconFactory ("md-vb-project-empty-project", "VB.Project.EmptyProject");
			AddToIconFactory ("md-vb-project-form", "VB.Project.Form");
			AddToIconFactory ("md-vb-project-full-project", "VB.Project.FullProject");
			AddToIconFactory ("md-vb-project-icon", "VB.ProjectIcon");
			AddToIconFactory ("md-vb-project-library", "VB.Project.Library");
			AddToIconFactory ("md-vb-project-service-project", "VB.Project.ServiceProject");
			AddToIconFactory ("md-vb-project-user-control", "VB.Project.UserControl");
			AddToIconFactory ("md-vb-project-web-project", "VB.Project.WebProject");
			AddToIconFactory ("md-warning", "Icons.16x16.Warning", Gtk.IconSize.Menu);
			AddToIconFactory ("md-warning", "Icons.32x32.Warning", Gtk.IconSize.Dnd);
			AddToIconFactory ("md-web-search-icon", "Icons.16x16.WebSearchIcon");
			AddToIconFactory ("md-xml-file-icon", "Icons.16x16.XMLFileIcon", Gtk.IconSize.Menu);
			AddToIconFactory ("md-xml-file-icon", "Icons.32x32.XMLFileIcon", Gtk.IconSize.Dnd);
		}

		public static string AboutIcon { get { return "md-about-icon"; } }
		public static string AdjustBackgroundColor { get { return "md-adjust-background-color"; } }
		public static string AdjustColor { get { return "md-adjust-color"; } }
		public static string AspFileIcon { get { return "md-asp-file-icon"; } }
		public static string Assembly { get { return "md-assembly"; } }
		public static string BoldText { get { return "md-bold-text"; } }
		public static string BrowserAfter { get { return "md-browser-after"; } }
		public static string BrowserBefore { get { return "md-browser-before"; } }
		public static string BrowserCancel { get { return "md-browser-cancel"; } }
		public static string BrowserRefresh { get { return "md-browser-refresh"; } }
		public static string BuildCombine { get { return "md-build-combine"; } }
		public static string BuildCurrentSelectedProject { get { return "md-build-current-selected-project"; } }
		public static string CPlusPlusFileEmptyFile { get { return "md-c++-file-empty-file"; } }
		public static string CPlusPlusFileForm { get { return "md-c++-file-form"; } }
		public static string CPlusPlusFileFullFile { get { return "md-c++-file-full-file"; } }
		public static string CPlusPlusFileIcon { get { return "md-c++-file-icon"; } }
		public static string CPlusPlusFileNewClass { get { return "md-c++-file-new-class"; } }
		public static string CPlusPlusFileWebFile { get { return "md-c++-file-web-file"; } }
		public static string CPlusPlusProjectDosProject { get { return "md-c++-project-dos-project"; } }
		public static string CPlusPlusProjectEmptyProject { get { return "md-c++-project-empty-project"; } }
		public static string CPlusPlusProjectForm { get { return "md-c++-project-form"; } }
		public static string CPlusPlusProjectFullProject { get { return "md-c++-project-full-project"; } }
		public static string CPlusPlusProjectIcon { get { return "md-c++-project-icon"; } }
		public static string CPlusPlusProjectLibrary { get { return "md-c++-project-library"; } }
		public static string CPlusPlusProjectServiceProject { get { return "md-c++-project-service-project"; } }
		public static string CPlusPlusProjectUserControl { get { return "md-c++-project-user-control"; } }
		public static string CPlusPlusProjectWebProject { get { return "md-c++-project-web-project"; } }
		public static string CSharpFileEmptyFile { get { return "md-c#-file-empty-file"; } }
		public static string CSharpFileForm { get { return "md-c#-file-form"; } }
		public static string CSharpFileFullFile { get { return "md-c#-file-full-file"; } }
		public static string CSharpFileIcon { get { return "md-c#-file-icon"; } }
		public static string CSharpFileNewClass { get { return "md-c#-file-new-class"; } }
		public static string CSharpFileWebFile { get { return "md-c#-file-web-file"; } }
		public static string CSharpProjectDosProject { get { return "md-c#-project-dos-project"; } }
		public static string CSharpProjectEmptyProject { get { return "md-c#-project-empty-project"; } }
		public static string CSharpProjectForm { get { return "md-c#-project-form"; } }
		public static string CSharpProjectFullProject { get { return "md-c#-project-full-project"; } }
		public static string CSharpProjectIcon { get { return "md-c#-project-icon"; } }
		public static string CSharpProjectLibrary { get { return "md-c#-project-library"; } }
		public static string CSharpProjectServiceProject { get { return "md-c#-project-service-project"; } }
		public static string CSharpProjectUserControl { get { return "md-c#-project-user-control"; } }
		public static string CSharpProjectWebProject { get { return "md-c#-project-web-project"; } }
		public static string CancelIcon { get { return "md-cancel-icon"; } }
		public static string Cdrom { get { return "md-cdrom"; } }
		public static string Center { get { return "md-center"; } }
		public static string Class { get { return "md-class"; } }
		public static string ClassBrowserIcon { get { return "md-class-browser-icon"; } }
		public static string ClearAllBookmarks { get { return "md-clear-all-bookmarks"; } }
		public static string CloseAllDocuments { get { return "md-close-all-documents"; } }
		public static string CloseCombineIcon { get { return "md-close-combine-icon"; } }
		public static string ClosedFolderBitmap { get { return "md-closed-folder-bitmap"; } }
		public static string ClosedOptionFolder { get { return "md-closed-option-folder"; } }
		public static string ClosedReferenceFolder { get { return "md-closed-reference-folder"; } }
		public static string ClosedResourceFolder { get { return "md-closed-resource-folder"; } }
		public static string CombineIcon { get { return "md-combine-icon"; } }
		public static string CommentRegion { get { return "md-comment-region"; } }
		public static string CopyIcon { get { return "md-copy-icon"; } }
		public static string CopyLeftIcon { get { return "md-copy-left-icon"; } }
		public static string CutIcon { get { return "md-cut-icon"; } }
		public static string Delegate { get { return "md-delegate"; } }
		public static string DeleteIcon { get { return "md-delete-icon"; } }
		public static string DesignPanel { get { return "md-design-panel"; } }
		public static string Desktop { get { return "md-desktop"; } }
		public static string Drive { get { return "md-drive"; } }
		public static string Empty { get { return "md-empty"; } }
		public static string EmptyFileIcon { get { return "md-empty-file-icon"; } }
		public static string EmptyProjectIcon { get { return "md-empty-project-icon"; } }
		public static string Enum { get { return "md-enum"; } }
		public static string Error { get { return "md-error"; } }
		public static string Event { get { return "md-event"; } }
		public static string Field { get { return "md-field"; } }
		public static string FileScoutIcon { get { return "md-file-scout-icon"; } }
		public static string FileXmlIcon { get { return "md-file-xml-icon"; } }
		public static string FindIcon { get { return "md-find-icon"; } }
		public static string FindInFiles { get { return "md-find-in-files"; } }
		public static string FindNextIcon { get { return "md-find-next-icon"; } }
		public static string Floppy { get { return "md-floppy"; } }
		public static string FormsDesignerAlignBottoms { get { return "md-forms-designer-align-bottoms"; } }
		public static string FormsDesignerAlignCenters { get { return "md-forms-designer-align-centers"; } }
		public static string FormsDesignerAlignLefts { get { return "md-forms-designer-align-lefts"; } }
		public static string FormsDesignerAlignMiddles { get { return "md-forms-designer-align-middles"; } }
		public static string FormsDesignerAlignRights { get { return "md-forms-designer-align-rights"; } }
		public static string FormsDesignerAlignToGrid { get { return "md-forms-designer-align-to-grid"; } }
		public static string FormsDesignerAlignTops { get { return "md-forms-designer-align-tops"; } }
		public static string FormsDesignerBringToFront { get { return "md-forms-designer-bring-to-front"; } }
		public static string FormsDesignerCenterHorizontally { get { return "md-forms-designer-center-horizontally"; } }
		public static string FormsDesignerCenterVertically { get { return "md-forms-designer-center-vertically"; } }
		public static string FormsDesignerDecreaseHorizontalSpace { get { return "md-forms-designer-decrease-horizontal-space"; } }
		public static string FormsDesignerDecreaseVerticalSpace { get { return "md-forms-designer-decrease-vertical-space"; } }
		public static string FormsDesignerEqualizeHorizontalSpace { get { return "md-forms-designer-equalize-horizontal-space"; } }
		public static string FormsDesignerEqualizeVerticalSpace { get { return "md-forms-designer-equalize-vertical-space"; } }
		public static string FormsDesignerIncreaseHorizontalSpace { get { return "md-forms-designer-increase-horizontal-space"; } }
		public static string FormsDesignerIncreaseVerticalSpace { get { return "md-forms-designer-increase-vertical-space"; } }
		public static string FormsDesignerLockControls { get { return "md-forms-designer-lock-controls"; } }
		public static string FormsDesignerMakeSameHeight { get { return "md-forms-designer-make-same-height"; } }
		public static string FormsDesignerMakeSameSize { get { return "md-forms-designer-make-same-size"; } }
		public static string FormsDesignerMakeSameWidth { get { return "md-forms-designer-make-same-width"; } }
		public static string FormsDesignerPointerIcon { get { return "md-forms-designer-pointer-icon"; } }
		public static string FormsDesignerRemoveHorizontalSpace { get { return "md-forms-designer-remove-horizontal-space"; } }
		public static string FormsDesignerRemoveVerticalSpace { get { return "md-forms-designer-remove-vertical-space"; } }
		public static string FormsDesignerSendToBack { get { return "md-forms-designer-send-to-back"; } }
		public static string FormsDesignerShowTabOrder { get { return "md-forms-designer-show-tab-order"; } }
		public static string FormsDesignerSizeToGrid { get { return "md-forms-designer-size-to-grid"; } }
		public static string FormsDesignerViewCode { get { return "md-forms-designer-view-code"; } }
		public static string FullScreen { get { return "md-full-screen"; } }
		public static string GotoNextbookmark { get { return "md-goto-nextbookmark"; } }
		public static string GotoPrevbookmark { get { return "md-goto-prevbookmark"; } }
		public static string HelpClosedFolder { get { return "md-help-closed-folder"; } }
		public static string HelpIcon { get { return "md-help-icon"; } }
		public static string HelpOpenFolder { get { return "md-help-open-folder"; } }
		public static string HelpTopic { get { return "md-help-topic"; } }
		public static string HtmlClass { get { return "md-html-class"; } }
		public static string HtmlElementsAnchorElement { get { return "md-html-elements-anchor-element"; } }
		public static string HtmlElementsButtonElement { get { return "md-html-elements-button-element"; } }
		public static string HtmlElementsDivElement { get { return "md-html-elements-div-element"; } }
		public static string HtmlElementsElement { get { return "md-html-elements-element"; } }
		public static string HtmlElementsFieldSetElement { get { return "md-html-elements-field-set-element"; } }
		public static string HtmlElementsFormElement { get { return "md-html-elements-form-element"; } }
		public static string HtmlElementsHorizontalRuleElement { get { return "md-html-elements-horizontal-rule-element"; } }
		public static string HtmlElementsIFrameElement { get { return "md-html-elements-i-frame-element"; } }
		public static string HtmlElementsImageElement { get { return "md-html-elements-image-element"; } }
		public static string HtmlElementsInputButtonElement { get { return "md-html-elements-input-button-element"; } }
		public static string HtmlElementsInputCheckBoxElement { get { return "md-html-elements-input-check-box-element"; } }
		public static string HtmlElementsInputFileElement { get { return "md-html-elements-input-file-element"; } }
		public static string HtmlElementsInputHiddenElement { get { return "md-html-elements-input-hidden-element"; } }
		public static string HtmlElementsInputImageElement { get { return "md-html-elements-input-image-element"; } }
		public static string HtmlElementsInputPasswordElement { get { return "md-html-elements-input-password-element"; } }
		public static string HtmlElementsInputRadioElement { get { return "md-html-elements-input-radio-element"; } }
		public static string HtmlElementsInputResetElement { get { return "md-html-elements-input-reset-element"; } }
		public static string HtmlElementsInputSubmitElement { get { return "md-html-elements-input-submit-element"; } }
		public static string HtmlElementsInputTextElement { get { return "md-html-elements-input-text-element"; } }
		public static string HtmlElementsLabelElement { get { return "md-html-elements-label-element"; } }
		public static string HtmlElementsListBoxElement { get { return "md-html-elements-list-box-element"; } }
		public static string HtmlElementsPanelElement { get { return "md-html-elements-panel-element"; } }
		public static string HtmlElementsSelectElement { get { return "md-html-elements-select-element"; } }
		public static string HtmlElementsSpanElement { get { return "md-html-elements-span-element"; } }
		public static string HtmlElementsTableElement { get { return "md-html-elements-table-element"; } }
		public static string HtmlElementsTextAreaElement { get { return "md-html-elements-text-area-element"; } }
		public static string HtmlFileIcon { get { return "md-html-file-icon"; } }
		public static string HtmlIcon { get { return "md-html-icon"; } }
		public static string HtmlImplementation { get { return "md-html-implementation"; } }
		public static string HtmlNote { get { return "md-html-note"; } }
		public static string HtmlStructure { get { return "md-html-structure"; } }
		public static string Ildasm { get { return "md-ildasm"; } }
		public static string Indent { get { return "md-indent"; } }
		public static string Information { get { return "md-information"; } }
		public static string Interface { get { return "md-interface"; } }
		public static string InternalClass { get { return "md-internal-class"; } }
		public static string InternalDelegate { get { return "md-internal-delegate"; } }
		public static string InternalEnum { get { return "md-internal-enum"; } }
		public static string InternalEvent { get { return "md-internal-event"; } }
		public static string InternalField { get { return "md-internal-field"; } }
		public static string InternalInterface { get { return "md-internal-interface"; } }
		public static string InternalMethod { get { return "md-internal-method"; } }
		public static string InternalProperty { get { return "md-internal-property"; } }
		public static string InternalStruct { get { return "md-internal-struct"; } }
		public static string ItalicText { get { return "md-italic-text"; } }
		public static string JavaFileEmptyFile { get { return "md-java-file-empty-file"; } }
		public static string JavaFileForm { get { return "md-java-file-form"; } }
		public static string JavaFileFullFile { get { return "md-java-file-full-file"; } }
		public static string JavaFileIcon { get { return "md-java-file-icon"; } }
		public static string JavaFileNewClass { get { return "md-java-file-new-class"; } }
		public static string JavaFileWebFile { get { return "md-java-file-web-file"; } }
		public static string JavaProjectDosProject { get { return "md-java-project-dos-project"; } }
		public static string JavaProjectEmptyProject { get { return "md-java-project-empty-project"; } }
		public static string JavaProjectForm { get { return "md-java-project-form"; } }
		public static string JavaProjectFullProject { get { return "md-java-project-full-project"; } }
		public static string JavaProjectIcon { get { return "md-java-project-icon"; } }
		public static string JavaProjectLibrary { get { return "md-java-project-library"; } }
		public static string JavaProjectServiceProject { get { return "md-java-project-service-project"; } }
		public static string JavaProjectUserControl { get { return "md-java-project-user-control"; } }
		public static string JavaProjectWebProject { get { return "md-java-project-web-project"; } }
		public static string JscriptFileEmptyFile { get { return "md-jscript-file-empty-file"; } }
		public static string JscriptFileForm { get { return "md-jscript-file-form"; } }
		public static string JscriptFileFullFile { get { return "md-jscript-file-full-file"; } }
		public static string JscriptFileIcon { get { return "md-jscript-file-icon"; } }
		public static string JscriptFileNewClass { get { return "md-jscript-file-new-class"; } }
		public static string JscriptFileWebFile { get { return "md-jscript-file-web-file"; } }
		public static string JscriptProjectDosProject { get { return "md-jscript-project-dos-project"; } }
		public static string JscriptProjectEmptyProject { get { return "md-jscript-project-empty-project"; } }
		public static string JscriptProjectForm { get { return "md-jscript-project-form"; } }
		public static string JscriptProjectFullProject { get { return "md-jscript-project-full-project"; } }
		public static string JscriptProjectIcon { get { return "md-jscript-project-icon"; } }
		public static string JscriptProjectLibrary { get { return "md-jscript-project-library"; } }
		public static string JscriptProjectServiceProject { get { return "md-jscript-project-service-project"; } }
		public static string JscriptProjectUserControl { get { return "md-jscript-project-user-control"; } }
		public static string JscriptProjectWebProject { get { return "md-jscript-project-web-project"; } }
		public static string LargeIcon { get { return "md-large-icon"; } }
		public static string Left { get { return "md-left"; } }
		public static string Library { get { return "md-library"; } }
		public static string Literal { get { return "md-literal"; } }
		public static string LowerToUpperCase { get { return "md-lower-to-upper-case"; } }
		public static string Method { get { return "md-method"; } }
		public static string MiscFiles { get { return "md-misc-files"; } }
		public static string MyComputer { get { return "md-my-computer"; } }
		public static string NameSpace { get { return "md-name-space"; } }
		public static string Network { get { return "md-network"; } }
		public static string NewDocumentIcon { get { return "md-new-document-icon"; } }
		public static string NewFolderIcon { get { return "md-new-folder-icon"; } }
		public static string NewProjectIcon { get { return "md-new-project-icon"; } }
		public static string NextWindowIcon { get { return "md-next-window-icon"; } }
		public static string OpenAssembly { get { return "md-open-assembly"; } }
		public static string OpenFileIcon { get { return "md-open-file-icon"; } }
		public static string OpenFolderBitmap { get { return "md-open-folder-bitmap"; } }
		public static string OpenOptionFolder { get { return "md-open-option-folder"; } }
		public static string OpenProjectIcon { get { return "md-open-project-icon"; } }
		public static string OpenReferenceFolder { get { return "md-open-reference-folder"; } }
		public static string OpenResourceFolder { get { return "md-open-resource-folder"; } }
		public static string Options { get { return "md-options"; } }
		public static string OutDent { get { return "md-out-dent"; } }
		public static string OutputIcon { get { return "md-output-icon"; } }
		public static string PasteIcon { get { return "md-paste-icon"; } }
		public static string PersonalFiles { get { return "md-personal-files"; } }
		public static string PreView { get { return "md-pre-view"; } }
		public static string PrevWindowIcon { get { return "md-prev-window-icon"; } }
		public static string Print { get { return "md-print"; } }
		public static string PrivateClass { get { return "md-private-class"; } }
		public static string PrivateDelegate { get { return "md-private-delegate"; } }
		public static string PrivateEnum { get { return "md-private-enum"; } }
		public static string PrivateEvent { get { return "md-private-event"; } }
		public static string PrivateField { get { return "md-private-field"; } }
		public static string PrivateInterface { get { return "md-private-interface"; } }
		public static string PrivateMethod { get { return "md-private-method"; } }
		public static string PrivateProperty { get { return "md-private-property"; } }
		public static string PrivateStruct { get { return "md-private-struct"; } }
		public static string ProjectScoutIcon { get { return "md-project-scout-icon"; } }
		public static string PropertiesIcon { get { return "md-properties-icon"; } }
		public static string Property { get { return "md-property"; } }
		public static string ProtectedClass { get { return "md-protected-class"; } }
		public static string ProtectedDelegate { get { return "md-protected-delegate"; } }
		public static string ProtectedEnum { get { return "md-protected-enum"; } }
		public static string ProtectedEvent { get { return "md-protected-event"; } }
		public static string ProtectedField { get { return "md-protected-field"; } }
		public static string ProtectedInterface { get { return "md-protected-interface"; } }
		public static string ProtectedMethod { get { return "md-protected-method"; } }
		public static string ProtectedProperty { get { return "md-protected-property"; } }
		public static string ProtectedStruct { get { return "md-protected-struct"; } }
		public static string Question { get { return "md-question"; } }
		public static string RedoIcon { get { return "md-redo-icon"; } }
		public static string Reference { get { return "md-reference"; } }
		public static string ReplaceIcon { get { return "md-replace-icon"; } }
		public static string ReplaceInFiles { get { return "md-replace-in-files"; } }
		public static string ResourceEditorbmp { get { return "md-resource-editorbmp"; } }
		public static string ResourceEditorcursor { get { return "md-resource-editorcursor"; } }
		public static string ResourceEditoricon { get { return "md-resource-editoricon"; } }
		public static string ResourceEditorobj { get { return "md-resource-editorobj"; } }
		public static string ResourceEditorstring { get { return "md-resource-editorstring"; } }
		public static string ResourceFileIcon { get { return "md-resource-file-icon"; } }
		public static string Right { get { return "md-right"; } }
		public static string RunProgramIcon { get { return "md-run-program-icon"; } }
		public static string SaveAllIcon { get { return "md-save-all-icon"; } }
		public static string SaveIcon { get { return "md-save-icon"; } }
		public static string SelectionArrow { get { return "md-selection-arrow"; } }
		public static string SharpDevelopIcon { get { return "md-sharp-develop-icon"; } }
		public static string Shell { get { return "md-shell"; } }
		public static string SideBarDocument { get { return "md-side-bar-document"; } }
		public static string SmallIcon { get { return "md-small-icon"; } }
		public static string SolutionIcon { get { return "md-solution-icon"; } }
		public static string SplitWindow { get { return "md-split-window"; } }
		public static string Struct { get { return "md-struct"; } }
		public static string SubTypes { get { return "md-sub-types"; } }
		public static string SuperTypes { get { return "md-super-types"; } }
		public static string TaskListIcon { get { return "md-task-list-icon"; } }
		public static string TextFileIcon { get { return "md-text-file-icon"; } }
		public static string TipOfTheDay { get { return "md-tip-of-the-day"; } }
		public static string TipOfTheDayIcon { get { return "md-tip-of-the-day-icon"; } }
		public static string ToggleBookmark { get { return "md-toggle-bookmark"; } }
		public static string ToolBar { get { return "md-tool-bar"; } }
		public static string UnderlineText { get { return "md-underline-text"; } }
		public static string UndoIcon { get { return "md-undo-icon"; } }
		public static string UpperToLowerCase { get { return "md-upper-to-lower-case"; } }
		public static string VbFileEmptyFile { get { return "md-vb-file-empty-file"; } }
		public static string VbFileForm { get { return "md-vb-file-form"; } }
		public static string VbFileFullFile { get { return "md-vb-file-full-file"; } }
		public static string VbFileIcon { get { return "md-vb-file-icon"; } }
		public static string VbFileNewClass { get { return "md-vb-file-new-class"; } }
		public static string VbFileWebFile { get { return "md-vb-file-web-file"; } }
		public static string VbProjectDosProject { get { return "md-vb-project-dos-project"; } }
		public static string VbProjectEmptyProject { get { return "md-vb-project-empty-project"; } }
		public static string VbProjectForm { get { return "md-vb-project-form"; } }
		public static string VbProjectFullProject { get { return "md-vb-project-full-project"; } }
		public static string VbProjectIcon { get { return "md-vb-project-icon"; } }
		public static string VbProjectLibrary { get { return "md-vb-project-library"; } }
		public static string VbProjectServiceProject { get { return "md-vb-project-service-project"; } }
		public static string VbProjectUserControl { get { return "md-vb-project-user-control"; } }
		public static string VbProjectWebProject { get { return "md-vb-project-web-project"; } }
		public static string Warning { get { return "md-warning"; } }
		public static string WebSearchIcon { get { return "md-web-search-icon"; } }
		public static string XmlFileIcon { get { return "md-xml-file-icon"; } }
		
#endregion
	}
}

