#!/bin/bash

if test -n "$MOZILLA_FIVE_HOME"; then
	MOZILLA_HOME=$MOZILLA_FIVE_HOME
elif [ -f /usr/lib/mozilla-1.5/chrome/comm.jar ]; then
	MOZILLA_HOME=/usr/lib/mozilla-1.5
elif [ -f /usr/local/mozilla/chrome/comm.jar ]; then
	MOZILLA_HOME=/usr/local/mozilla
elif [ -f /usr/lib/mozilla/chrome/comm.jar ]; then
	MOZILLA_HOME=/usr/lib/mozilla
elif [ -f /opt/mozilla/chrome/comm.jar ]; then
	MOZILLA_HOME=/opt/mozilla
elif [ -f /usr/lib/mozilla-0.9.7/chrome/comm.jar ]; then
	MOZILLA_HOME=/usr/lib/mozilla-0.9.7/
elif [ -f /opt/gnome/lib/mozilla/chrome/comm.jar ]; then
        MOZILLA_HOME=/opt/gnome/lib/mozilla/
else
	echo "Cannot find mozilla installation directory. Please set MOZILLA_FIVE_HOME to your mozilla directory"
	exit 1
fi
 
GDLDOCKPATH=$(pwd)/build/bin

LD_LIBRARY_PATH=$MOZILLA_HOME:$GDLDOCK_PATH:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH
 
MOZILLA_FIVE_HOME=$MOZILLA_HOME
export MOZILLA_FIVE_HOME

cd build/bin

if test -n "$MD_NO_DBG"; then
	FLAGS=$MD_MONO_FLAGS
else
	FLAGS="$MD_MONO_FLAGS --debug"
fi
mono $FLAGS ./MonoDevelop.exe $@
