// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gdl {

	using System;

#region Autogenerated code
	public enum DockPlacement {

		None,
		Top,
		Bottom,
		Right,
		Left,
		Center,
		Floating,
	}
#endregion
}
