// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace Gdl {

	using System;

#region Autogenerated code
	public enum DockItemFlags {

		InDrag = 1,
		InPredrag = 2,
		UserAction = 3,
	}
#endregion
}
